# Generated by Django 3.2.12 on 2022-06-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.TextField(default='', null=True),
        ),
    ]
